# Generated by Django 5.2.6 on 2025-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='position',
            field=models.CharField(default='Candidato', max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('job', 'Entrevista de trabajo'), ('scholarship', 'Entrevista para beca'), ('practice', 'Práctica general'), ('mock', 'Simulación')], default='job', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('ai', 'IA')], max_length=10),
        ),
    ]
