# Generated by Django 5.2.6 on 2025-09-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_position_alter_interview_interview_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='language',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='level',
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('job', 'Entrevista de trabajo'), ('scholarship', 'Entrevista de beca'), ('informal', 'Conversación informal')], default='job', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('ai', 'Entrevistador IA'), ('feedback', 'Consejo IA')], max_length=20),
        ),
    ]
