# Generated by Django 5.2.6 on 2025-09-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_remove_interview_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='interview',
            name='asked_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=10),
        ),
        migrations.AddField(
            model_name='interview',
            name='level',
            field=models.CharField(choices=[('junior', 'Junior'), ('semi', 'Semi-Senior'), ('senior', 'Senior')], default='junior', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='max_questions',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('job', 'Trabajo'), ('academic', 'Académica'), ('scholarship', 'Beca'), ('informal', 'Informal')], max_length=20),
        ),
    ]
