# Generated by Django 5.2.6 on 2025-09-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_remove_interview_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('questions', 'Por número de preguntas'), ('time', 'Por tiempo')], default='questions', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='max_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
