# Generated by Django 5.2.6 on 2025-09-23 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_interview_mode_interview_time_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claridad', models.IntegerField(default=0)),
                ('confianza', models.IntegerField(default=0)),
                ('contenido', models.IntegerField(default=0)),
                ('creatividad', models.IntegerField(default=0)),
                ('lenguaje', models.IntegerField(default=0)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='interviews.message')),
            ],
        ),
    ]
